services:
  OxidEsales\EshopCommunity\Internal\Adapter\ShopAdapterInterface:
    class: OxidEsales\EshopCommunity\Internal\Adapter\ShopAdapter
    autowire: true
    public: false

# TemplateLogic
  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\InputhelpLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\InputhelpLogic